name: Build Windows Executable with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Specify Python version compatible with your script

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Compile with Nuitka
      - name: Compile with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: "font previewer.py"
          mode: onefile
          enable-plugins: pyside6
          windows-icon-from-ico: resources/Icon.ico
          include-data-dir: resources=resources
          windows-console-mode: disable

      # Step 5: Upload artifact
      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: FontPreviewerExecutable
          path: build/font previewer.exe
          include-hidden-files: true
